import Header from './components/header/header';
import './globals.css';
import RecoilContextProvider from './recoil/recoilContextProvider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <RecoilContextProvider>
          <Header />
          {children}
          <div id="modal-root"></div>
        </RecoilContextProvider>
      </body>
    </html>
  );
}
