import Header from './components/header/header';
import './globals.css';
import RecoilContextProvider from './recoil/recoilContextProvider';
import { headers } from 'next/headers';
import React from 'react';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode;
}) {
  const pathname = headers().get('x-next-pathname');
  const isIndex = pathname === '/';

  return (
    <html lang="ko">
    <body>
    <RecoilContextProvider>
      {!isIndex && (
        <Header />
      )}
      {children}
      <div id="modal-root"></div>
    </RecoilContextProvider>
    </body>
    </html>
  );
}
