import './globals.css'
import RecoilContextProvider from './recoil/recoilContextProvider'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body>
        <RecoilContextProvider>
          {children}
        </RecoilContextProvider>
      </body>
    </html>
  )
}
